<?php
/**
 * Created by PhpStorm.
 * User: spookee
 * Date: 10.12.18
 * Time: 14:03
 */

require_once __DIR__ . '/../class/Helper.php';

class Mollie extends PaymentMethod
{

    const MOLLIE_METHOD = "";
    /**
     * @var \ws_mollie\Helper
     */
    protected static $_helper;

    protected static $_mollie;


    public function __construct($moduleID, $nAgainCheckout = 0)
    {
        parent::__construct($moduleID, $nAgainCheckout);
        \ws_mollie\Helper::init();
    }

    /**
     * @return \Mollie\Api\MollieApiClient
     * @throws \Mollie\Api\Exceptions\ApiException
     * @throws \Mollie\Api\Exceptions\IncompatiblePlatform
     */
    public static function API()
    {
        if (self::$_mollie === null) {
            self::$_mollie = new \Mollie\Api\MollieApiClient();
            self::$_mollie->setApiKey(\ws_mollie\Helper::getSetting('api_key'));
        }
        return self::$_mollie;
    }

    /**
     * @return \ws_mollie\Helper
     */
    public static function Helper()
    {
        if (self::$_helper === null) {
            self::$_helper = new ws_mollie\Helper();
        }
        return self::$_helper;
    }

    /**
     * Prepares everything so that the Customer can start the Payment Process.
     * Tells Template Engine.
     *
     * @param Bestellung $order
     */
    public function preparePaymentProcess($order)
    {
        $data = [
            'amount' => [
                'currency' => $order->Waehrung->cISO,
                'value' => number_format($order->fGesamtsumme, 2, '.', ''),
            ],
            'description' => 'Ihre Bestellung bei XXX: ' . $order->cBestellNr,
            'redirectUrl' => $this->getReturnURL($order),
            'webhookUrl' => $this->getNotificationURL($this->generateHash($order))
        ];
        try {
            $oMolliePayment = static::API()->payments->create($data);
            $this->doLog('Mollie Create Payment Redirect: ' . $oMolliePayment->getCheckoutUrl());
            Shop::Smarty()->assign('oMolliePayment', $oMolliePayment);
            header('Location: ' . $oMolliePayment->getCheckoutUrl());
            exit();
        } catch (\Mollie\Api\Exceptions\ApiException $e) {
            Shop::Smarty()->assign('oMollieException', $e);
            $this->doLog("Create Payment Error: " . $e->getMessage() . '<br/>><pre>' . print_r($data, 1) . '</pre>');
        }
    }

    /**
     * @param Bestellung $order
     * @param string $hash
     * @param array $args
     */
    public function handleNotification($order, $hash, $args)
    {

    }

    /**
     * @param Bestellung $order
     * @param string $hash
     * @param array $args
     *
     * @return true, if $order should be finalized
     */
    public function finalizeOrder($order, $hash, $args)
    {
        return false;
    }

    /**
     * @return bool
     */
    public function canPayAgain()
    {
        return true;
    }

    /**
     * determines, if the payment method can be selected in the checkout process
     *
     * @return bool
     */
    public function isSelectable()
    {
        return true;
    }

    /**
     *
     * @param object $customer
     * @param Warenkorb $cart
     * @return bool - true, if $customer with $cart may use Payment Method
     */
    public function isValid($customer, $cart)
    {
        if (\ws_mollie\Helper::init() && \ws_mollie\Helper::getSetting("api_key")) {
            return true;
        }
        $this->doLog("isValdid failed: init failed or no API Key given. Try clear the Cache.");
        return false;
    }

    /**
     * @param array $args_arr
     * @return bool
     */
    public function isValidIntern($args_arr = [])
    {
        if (\ws_mollie\Helper::init() && \ws_mollie\Helper::getSetting("api_key")) {
            return true;
        }
        $this->doLog("isValdid failed: init failed or no API Key given. Try clear the Cache.");
        return false;
    }

    /**
     * @return bool
     */
    public function redirectOnCancel()
    {
        return parent::redirectOnCancel(); // TODO: Change the autogenerated stub
    }
}